FROM debian:latest

WORKDIR /apps

RUN apt update && apt upgrade -y && apt install -y \
curl \
apt-transport-https \
lsb-release \
gnupg && \
curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
apt install -y nodejs && \
npm install -g vue-cli

CMD ["bash"]
